---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: All Apps deployed using Argo CD
  sourceRepos:
  - '*'
  destinations:
  - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: {{.Values.onboarding.repo}}
    targetRevision: {{.Values.onboarding.branch}}
    path: {{.Values.onboarding.folder}}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: true
    syncOptions:    
    - ServerSideApply=true
    - CreateNamespace=true 
    