apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: {{.Values.acme.email}}
    server: https://acme-staging-v02.api.letsencrypt.org./directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones: [] # all?
        dns01:
          route53:
            region: {{.Values.region}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: {{.Values.acme.email}}
    server: https://acme-v02.api.letsencrypt.org./directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones: [] # all?
        dns01:
          route53:
            region: {{.Values.region}}